DROP TABLE IF EXISTS Product;

CREATE TABLE Product (
                              id INT AUTO_INCREMENT  PRIMARY KEY,
                              name VARCHAR(250),
                              pic_dest VARCHAR(250),
                              number_of_items_remaining INT,
                              price INT
);

INSERT INTO Product (name, pic_dest, number_of_items_remaining, price) VALUES
('Apple', 'products/apple.jpeg', 4, 18),
('Banana', 'products/banana.jfif', 8, 5),
('Chocolate Slab', 'products/chocolate%20slab.png', 10, 25),
('Coke', 'products/coke.jfif', 6, 18),
('Powerade', 'products/powerade.png', 8, 28),
('Liquifruit', 'products/liquifruit.webp', 3, 18),
('Mayo', 'products/mayo.png', 9, 18),
('7up', 'products/7up.jpg', 5, 23),
('Candied Peanuts', 'products/candied%20peanuts.jpg', 5, 23),
('Appletiser', 'products/Appletiser.jpg', 5, 23),
('BarOne', 'products/barone.png', 5, 23),
('Crunchie', 'products/Cadbury_Crunchie_61_0.png', 5, 23),
('Candarel Dark Chocolate', 'products/Candarel Dark Chocolate.png', 5, 23),
('Candy Andy', 'products/candy andy.jpg', 5, 23),
('Cappy', 'products/Cappy.png', 5, 23),
('Ceres', 'products/Ceres.jfif', 5, 23),
('Frozen Yogurt', 'products/frozen yogurt.jfif', 5, 23),
('Chocolate Milkshake', 'products/Chocolate Milkshake.jfif', 5, 23),
('Green Grapes', 'products/Green Grapes.jfif', 5, 23),
('Krush Juice', 'products/Krush Juice.jpg', 5, 23),
('Kingsley Cola', 'products/Kingsley Cola.jpg', 5, 23),
('Just Juice', 'products/Just Juice.jpg', 5, 23),
('Grapefruit', 'products/Grapefruit-in-season-1.jpg', 5, 23),
('Rascals', 'products/Rascals.png', 5, 23),
('Iron Brew', 'products/Iron Brew.jpeg', 5, 23),
('Kit Kat', 'products/kitkat.webp', 5, 23),
('Maynards', 'products/maynards.jpg', 5, 23),
('M&Ms', 'products/m&ms.png', 5, 23),
('Twinkies', 'products/moonberry-twinkies-FT-BLOG0819.jpg', 5, 23),
('Speckled Eggs', 'products/new-speckled-eggs-125g.png', 5, 23),
('Minute Maid', 'products/MInute Maid.jpg', 5, 23),
('Orange', 'products/orange.jfif', 5, 23),
('Pepsi', 'products/PEPSI-COLA-CAN-300ml.jpg', 5, 23),
('Pear', 'products/pear.jpg', 5, 23),
('Pin Pop', 'products/pin pop.jpg', 5, 23),
('Iced Coffee', 'products/Tia-Maria-Iced-Coffee.jpg', 5, 23),
('Spar-Letta', 'products/Sparletta.jpg', 5, 23),
('Take 5', 'products/take-5-products-juices-1.5l-juice-fruit-and-vegetable-600x600.jpg', 5, 23),
('Sir Fruit', 'products/Sir Fruit.png', 5, 23),
('Softmints', 'products/Softmints.jpeg', 5, 23),
('Sour Worms', 'products/Sour worms.jpeg', 5, 23),
('Fanta Grape', 'products/fanta grape.png', 5, 23),
('Fanta Orange', 'products/fanta orange.png', 5, 23),
('Ice Tea', 'products/Ice Tea.jfif', 5, 23),
('JawBreaker', 'products/Jawbreaker.jfif', 5, 23),
('Simba', 'products/simba.png', 5, 23),
('Snickers', 'products/snickers.jpg', 10, 18);